---
title: "Homework 1"
author: Jingyi Zhang
output: github_document
---

This is my solution to HW1.

```{r load_package}
library(tidyverse)
data("penguins", package = "palmerpenguins")
```


## Problem 1

Create a data frame with the specified elements.

```{r create_df}
prob1_df = 
  tibble(
    samp = rnorm(10),
    samp_gt_0 = samp > 0,
    char_vec = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
    factor_vec = factor(c("low", "low", "low", "mod", "mod", "mod", "mod", "high", "high", "high"))
)
```

Take the mean of each variable in my data frame.

```{r mean_pull_var}
mean(pull(prob1_df, samp))
mean(pull(prob1_df, samp_gt_0))
mean(pull(prob1_df, char_vec))
mean(pull(prob1_df, factor_vec))
```

I can take the mean of numbers and logical but not character or factor.

```{r try_numeric}
as.numeric(pull(prob1_df, samp))
as.numeric(pull(prob1_df, samp_gt_0))
as.numeric(pull(prob1_df, char_vec))
as.numeric(pull(prob1_df, factor_vec))
```

```{r covert_logical_vector}
as.numeric(pull(prob1_df, samp_gt_0)) * pull(prob1_df, samp)
as.factor(pull(prob1_df, samp_gt_0)) * pull(prob1_df, samp)
as.numeric(as.factor(pull(prob1_df, samp_gt_0))) * pull(prob1_df, samp)
```


## Problem 2

Write a short description of the penguins dataset.

```{r description_of_penguins}
as_tibble(penguins)
nrow(penguins)
ncol(penguins)
mean(penguins$flipper_length_mm, na.rm = TRUE)
```


make a scatterplot 

```{r}

```


